src/main/java/transmanager/entities/AbstractEntity.java
package transmanager.entities;


import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class AbstractEntity {
    @Id
    @GeneratedValue
    private int id;
    private boolean active;

    public AbstractEntity() {
        active = true;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}

src/main/java/transmanager/entities/Bankinfo.java
package transmanager.entities;

import javax.persistence.Entity;

@Entity
public class Bankinfo extends AbstractEntity {
    String name;
    String rs;
    String ks;
    String bik;
    String inn;
    String ogrn;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRs() {
        return rs;
    }

    public void setRs(String rs) {
        this.rs = rs;
    }

    public String getKs() {
        return ks;
    }

    public void setKs(String ks) {
        this.ks = ks;
    }

    public String getBik() {
        return bik;
    }

    public void setBik(String bik) {
        this.bik = bik;
    }

    public String getInn() {
        return inn;
    }

    public void setInn(String inn) {
        this.inn = inn;
    }

    public String getOgrn() {
        return ogrn;
    }

    public void setOgrn(String ogrn) {
        this.ogrn = ogrn;
    }
}

src/main/java/transmanager/entities/Car.java
package transmanager.entities;

import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import java.math.BigDecimal;

@NamedQuery(name = "getAllCars", query = "select d from Car d where  d.active = true")
@Entity
public class Car extends AbstractEntity {

    String carBrand;
    String number;
    String trailerNumber;
    String techInspect;
    String type;
    BigDecimal tonnage;
    BigDecimal capacity;
    BigDecimal volume;
    String comment;

    public String getCarBrand() {
        return carBrand;
    }

    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getTrailerNumber() {
        return trailerNumber;
    }

    public void setTrailerNumber(String trailerNumber) {
        this.trailerNumber = trailerNumber;
    }

    public String getTechInspect() {
        return techInspect;
    }

    public void setTechInspect(String techInspect) {
        this.techInspect = techInspect;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public BigDecimal getTonnage() {
        return tonnage;
    }

    public void setTonnage(BigDecimal tonnage) {
        this.tonnage = tonnage;
    }

    public BigDecimal getCapacity() {
        return capacity;
    }

    public void setCapacity(BigDecimal capacity) {
        this.capacity = capacity;
    }

    public BigDecimal getVolume() {
        return volume;
    }

    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}

src/main/java/transmanager/entities/Customer.java
package transmanager.entities;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@NamedQuery(name = "getAllCustomers", query = "select d from Customer d where d.active = true")
@Entity
public class Customer extends AbstractEntity {
    @OneToOne(cascade = CascadeType.ALL)
    private Organization org;
    @OneToMany(cascade = CascadeType.ALL)
    private List<Route> routes;

    public Customer() {
        routes = new ArrayList<Route>();
        org = new Organization();
    }

    //region getters and setters
    public Organization getOrg() {
        return org;
    }

    public void setOrg(Organization org) {
        this.org = org;
    }

    public List<Route> getRoutes() {
        return routes;
    }

    public void setRoutes(List<Route> routes) {
        this.routes = routes;
    }
    //endregion
}

src/main/java/transmanager/entities/Driver.java
package transmanager.entities;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@NamedQuery(name = "getAllDrivers", query = "select d from Driver d where d.active = true")
@Entity
public class Driver extends AbstractEntity {
    @Size(min = 1, message = "{no_empty_str}")
    String name;

    @Size(min = 1, message = "{no_empty_str}")
    String driverLicense;

    @Pattern(regexp = "[[0-9]{1,3}-[0-9]{1,3}]+")
    String phoneNumber;

    @Size(min = 1, message = "{no_empty_str}")
    String passportDetails;

    @OneToOne(cascade = CascadeType.ALL)
    Location registrationAdress;

    @OneToOne(cascade = CascadeType.ALL)
    Location realAdress;

    public Driver() {
        realAdress = new Location();
        registrationAdress = new Location();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDriverLicense() {
        return driverLicense;
    }

    public void setDriverLicense(String driverLicense) {
        this.driverLicense = driverLicense;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPassportDetails() {
        return passportDetails;
    }

    public void setPassportDetails(String passportDetails) {
        this.passportDetails = passportDetails;
    }

    public Location getRegistrationAdress() {
        return registrationAdress;
    }

    public void setRegistrationAdress(Location registrationAdress) {
        this.registrationAdress = registrationAdress;
    }

    public Location getRealAdress() {
        return realAdress;
    }

    public void setRealAdress(Location realAdress) {
        this.realAdress = realAdress;
    }
}

src/main/java/transmanager/entities/Location.java
package transmanager.entities;

import javax.persistence.Entity;

@Entity
public class Location extends AbstractEntity {

    String fullAddress;

    public String getFullAddress() {
        return fullAddress;
    }

    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress;
    }
}

src/main/java/transmanager/entities/Route.java
package transmanager.entities;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

@Entity
public class Route extends AbstractEntity {
    @OneToOne(cascade = CascadeType.ALL)
    private Location loadingAddress;
    @OneToOne(cascade = CascadeType.ALL)
    private Location unloadingAddress;
    private String name;

    public Route() {
        loadingAddress = new Location();
        unloadingAddress = new Location();
    }

    //region getters and setters
    public Location getLoadingAddress() {
        return loadingAddress;
    }

    public void setLoadingAddress(Location loadingAddress) {
        this.loadingAddress = loadingAddress;
    }

    public Location getUnloadingAddress() {
        return unloadingAddress;
    }

    public void setUnloadingAddress(Location unloadingAddress) {
        this.unloadingAddress = unloadingAddress;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    //endregion
}

src/main/java/transmanager/entities/package-info.java
@XmlJavaTypeAdapter(value = CalendarAdaptor.class, type = Calendar.class)
@XmlAccessorType(XmlAccessType.FIELD)
package transmanager.entities;

import transmanager.xmladaptor.CalendarAdaptor;
import transmanager.xmladaptor.SanctionsAdaptor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Calendar;
import java.util.List;

src/main/java/transmanager/controllers/AbstractEntitiesController.java
package transmanager.controllers;


import transmanager.ejb.AbstractEntityBean;
import transmanager.entities.AbstractEntity;
import transmanager.entities.Car;
import transmanager.utils.URL;

import java.util.List;

public abstract class AbstractEntitiesController<T extends AbstractEntity> {
    private String page;
    private String editPage;
    protected abstract AbstractEntityBean getBean();

    public AbstractEntitiesController() {

    }

    protected AbstractEntitiesController(String page, String editPage) {
        this.page = page;
        this.editPage = editPage;
    }

    public List<T> getAll() {
        return getBean().getAll();
    }

    public int getCount() {
        return getBean().getAll().size();
    }

    public String delete(int id) {
        getBean().delete(id);
        return URL.redTo(page).go();
    }

    public String edit(int id) {
        return URL.redTo(editPage).add("id", id).go();
    }
}
/*


 */

src/main/java/transmanager/controllers/CarController.java
package transmanager.controllers;

import transmanager.ejb.CarBean;
import transmanager.entities.Car;
import transmanager.utils.URL;

import javax.ejb.EJB;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class CarController {
    @EJB
    CarBean carBean;

    private Car currentCar;

    public CarController() {
        this.currentCar = new Car();
    }

    //region Methods
    public String doCreate() {
        carBean.create(currentCar);
        return URL.redTo("cars").go();
    }

    public String update() {
        carBean.update(currentCar);
        return URL.redTo("cars").go();
    }

    public void init(ComponentSystemEvent event) throws AbortProcessingException {
        currentCar = carBean.getById(currentCar.getId());
    }
    //endregion

    //region Grtters and Setters
    public Car getCurrentCar() {
        if (currentCar == null)
            currentCar = new Car();
        return currentCar;
    }

    public void setCurrentCar(Car currentCar) {
        this.currentCar = currentCar;
    }
    //endregion

}

src/main/java/transmanager/controllers/CarsController.java
package transmanager.controllers;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import transmanager.ejb.AbstractEntityBean;
import transmanager.ejb.CarBean;
import transmanager.entities.Car;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class CarsController extends AbstractEntitiesController<Car> {
    @EJB
    private CarBean carBean;
    private static Logger logger = LogManager.getLogger(CarsController.class.getName());

    public CarsController() {
        super("cars", "editCar");
    }

    @Override
    protected AbstractEntityBean getBean() {
        return carBean;
    }
}

src/main/java/transmanager/controllers/CustomerController.java
package transmanager.controllers;

import transmanager.ejb.CustomerBean;
import transmanager.entities.Customer;
import transmanager.entities.Route;
import transmanager.utils.URL;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.List;

@Named
@ViewScoped
public class CustomerController {
    @EJB
    private CustomerBean customerBean;

    private Customer current;

    public CustomerController() {
        current = new Customer();
    }

    //region Methods
    public String doCreate() {
        customerBean.create(current);
        return URL.redTo("customers").go();
    }

    public String update() {
        customerBean.update(current);
        return URL.redTo("customers").go();
    }

    public String toSanctions() {
        return URL.redTo("organizationSanctions").add("id", current.getOrg().getId()).go();
    }

    public String toRoutes() {
        return URL.redTo("customerRoutes").add("id", current.getId()).go();
    }

    public String toCreateRoute() {
        return URL.redTo("createRoute").add("customerId", current.getId()).go();
    }

    public String toEditRoute(int routeId) {
        return URL.redTo("editRoute").add("id", routeId).add("customerId", current.getId()).go();
    }

    public List<Route> getRoutes(Integer customerId) {
        if(customerId != null)
            return customerBean.getRoutes(customerId);
        return new ArrayList<Route>();
    }

    public List<Route> getRoutes() {
        return customerBean.getRoutes(current.getId());
    }

    public void init() {
        current = customerBean.getById(current.getId());
    }
    //endregion

    //region Getters and Setters
    public Customer getCurrent() {
        return current;
    }

    public void setCurrent(Customer current) {
        this.current = current;
    }
    //endregion
}

src/main/java/transmanager/controllers/CustomersController.java
package transmanager.controllers;

import transmanager.ejb.AbstractEntityBean;
import transmanager.ejb.CustomerBean;
import transmanager.entities.Customer;
import transmanager.entities.Route;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.util.List;

@Named
@ViewScoped
public class CustomersController extends AbstractEntitiesController<Customer> {
    @EJB
    private CustomerBean customerBean;

    public CustomersController() {
        super("customers", "editCustomer");
    }

    @Override
    protected AbstractEntityBean getBean() {
        return customerBean;
    }
}

src/main/java/transmanager/controllers/DriverController.java
package transmanager.controllers;

import transmanager.ejb.DriverBean;
import transmanager.entities.Driver;
import transmanager.utils.URL;

import javax.ejb.EJB;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class DriverController {

    @EJB
    DriverBean driverBean;

    private Driver currentDriver;

    public DriverController() {
        this.currentDriver = new Driver();
    }

    //region Methods
    public String doCreate() {
        driverBean.create(currentDriver);
        return URL.redTo("drivers").go();
    }

    public String update() {
        driverBean.update(currentDriver);
        return URL.redTo("drivers").go();
    }

    public void init(ComponentSystemEvent event) throws AbortProcessingException {
        currentDriver = driverBean.getById(currentDriver.getId());
    }
    //endregion

    //region Getters and Setters
    public Driver getCurrentDriver() {
        if (currentDriver == null)
            currentDriver = new Driver();
        return currentDriver;
    }

    public void setCurrentDriver(Driver currentDriver) {
        this.currentDriver = currentDriver;
    }
    //endregion
}

src/main/java/transmanager/controllers/DriversController.java
package transmanager.controllers;

import transmanager.ejb.AbstractEntityBean;
import transmanager.ejb.DriverBean;
import transmanager.entities.Driver;
import transmanager.utils.URL;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.util.List;

@Named
@ViewScoped
public class DriversController extends AbstractEntitiesController<Driver>{
    @EJB
    private DriverBean driverBean;

    public DriversController() {
        super("drivers", "editDriver");
    }

    //region Methods
    public String deleteDriver(int id) {
        driverBean.delete(id);
        return URL.redTo("drivers").go();
    }

    public String editDriver(int id) {
        return URL.redTo("editDriver").add("id",id).go();
    }
    //endregion

    //region Getters and Setters
    public int getDriversCount() {
        return driverBean.getAll().size();
    }

    @Override
    protected AbstractEntityBean getBean() {
        return null;
    }

    public List<Driver> getAllDrivers() {
        return driverBean.getAll();
    }

    //endregion
}

src/main/java/transmanager/controllers/LocationController.java
package transmanager.controllers;


import transmanager.ejb.LocationBean;
import transmanager.entities.Location;
import transmanager.utils.JSFParameterHelper;

import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class LocationController {

    @EJB
    LocationBean locationBean;

    Location currentLocation;
    String url;

    LocationController() {
        currentLocation = new Location();
    }

    //region Methods
    public String update() {
        locationBean.update(currentLocation);
        return JSFParameterHelper.decodeUrlParam(url);
    }

    public void init() {
        currentLocation = locationBean.getById(currentLocation.getId());
    }
    //endregion

    //region Getters and Setters
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Location getCurrentLocation() {
        return currentLocation;
    }

    public void setCurrentLocation(Location currentLocation) {
        this.currentLocation = currentLocation;
    }
    //endregion
}

src/main/webapp/cars.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="layout.xhtml"
        >
    <ui:define name="content">
        <label>#{titles['car.count']}: #{carsController.count}</label>
        <br/>
        <h:link value="#{titles['button.create']}" outcome="createCar"/>
        <br/>
        <h:dataTable value="#{carsController.all}" var="car"
                     styleClass="tabl" headerClass="header"
                     rowClasses="tab_row_even, tab_row_odd"
                     columnClasses="col_name, col_second, col_fiction, col_edit, col_delete"
                >

            <h:column>
                <f:facet name="header">#{titles['entity.car.brand']}</f:facet>
                #{car.carBrand}
            </h:column>

            <h:column>
                <f:facet name="header">#{titles['entity.car.number']}</f:facet>
                #{car.number}
            </h:column>

            <h:column>
                <f:facet name="header"></f:facet>
            </h:column>

            <h:column>
                <h:form>
                    <h:commandLink value="#{titles['button.edit']}" action="#{carsController.edit(car.id)}"/>
                </h:form>
            </h:column>

            <h:column>
                <h:form>
                    <h:commandLink value="#{titles['button.delete']}" action="#{carsController.delete(car.id)}"/>
                </h:form>
            </h:column>

        </h:dataTable>


    </ui:define>
</ui:composition>

src/main/webapp/createCustomer.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="layout.xhtml"
        >
    <ui:define name="content">
        <h:form styleClass="form_details">
            <label class="title_view">#{titles['createCustomer.title']}</label>
            <ui:include src="customerView.xhtml"/>
            <h:commandLink value="#{titles['button.create']}"
                           action="#{customerController.doCreate}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/createDriver.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="layout.xhtml"
        >
    <ui:define name="content">
        <h:form styleClass="form_details">
            <label class="title_view">#{titles['driverCreate.title']}</label>
            <ui:include src="driverView.xhtml"/>
            <h:commandLink value="#{titles['button.create']}" action="#{driverController.doCreate}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/createTransporter.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="layout.xhtml"
        >
    <ui:define name="content">
        <h:form styleClass="form_details">
            <label class="title_view">#{titles['transporterCreate.title']}</label>
            <ui:include src="transporterView.xhtml"/>
            <h:commandLink value="#{titles['button.create']}"
                           action="#{transporterController.doCreate}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/createUnloadingAddress.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        template="layout.xhtml"
        >
    <ui:define name="metadata">
        <f:metadata>
            <f:viewParam name="id" value="#{organizationController.currentContragent.id}"/>
            <f:event type="preRenderView" listener="#{organizationController.init}"/>
        </f:metadata>
    </ui:define>
    <ui:define name="content">
        <h:form styleClass="form_details">
            <label class="title_view">#{titles['createUnloadingAddress.title']}</label>
            <ui:include src="locationView.xhtml"/>
            <h:commandLink value="#{titles['button.create']}"
                           action="#{organizationController.addUnloadingAddress(locationController.currentLocation)}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/customerView.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:composite="http://xmlns.jcp.org/jsf/composite"
                xmlns:custom="http://xmlns.jcp.org/jsf/composite/custom"
        >
    <custom:organizationView organization="#{customerController.current.org}"/>
</ui:composition>

src/main/webapp/requestView.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        >

    <h:panelGrid columns="3"
                 styleClass="png_details"
                 columnClasses="pngCol_lable, pngCol_input, pngCol_errors"
            >

        <label>#{titles['entity.request.number']}: </label>
        <h:inputText id="rqvNumber" value="#{requestController.current.number}"/>
        <h:message for="rqvNumber"/>

        <label>#{titles['entity.request.currenDate']}: </label>
        <h:inputText id="rqvCurrntDate" value="#{requestController.current.currentDate.time}">
            <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
        </h:inputText>
        <h:message for="rqvCurrntDate"/>

        <label>#{titles['entity.request.cost']}: </label>
        <h:inputText id="cost" value="#{requestController.current.cost}"/>
        <h:message for="cost"/>

        <label>#{titles['entity.request.responsiblePersonName']}: </label>
        <h:inputText id="responsiblePersonName" value="#{requestController.current.responsiblePersonName}"/>
        <h:message for="responsiblePersonName"/>

        <label>#{titles['entity.request.responsiblePersonPhone']}: </label>
        <h:inputText id="responsiblePersonPhone" value="#{requestController.current.responsiblePersonPhone}"/>
        <h:message for="responsiblePersonPhone"/>

        <label>#{titles['entity.request.loadingTime']}: </label>
        <h:inputText id="loadingTime" value="#{requestController.current.loadingTime.time}">
            <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
        </h:inputText>
        <h:message for="loadingTime"/>

        <label>#{titles['entity.request.unloadingTime']}: </label>
        <h:inputText id="unloadingTime" value="#{requestController.current.unloadingTime.time}">
            <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
        </h:inputText>
        <h:message for="unloadingTime"/>

        <label>#{titles['entity.request.driver']}</label>
        <h:selectOneMenu id="drv" value="#{requestController.current.driverId}">
            <f:selectItem itemLabel="  " noSelectionOption="true"/>
            <f:selectItems value="#{driversController.allDrivers}" var="drv" itemLabel="#{drv.name}"
                           itemValue="#{drv.id}"/>
        </h:selectOneMenu>
        <h:message for="drv"/>

        <label>#{titles['entity.request.car']}</label>
        <h:selectOneMenu id="car" value="#{requestController.current.carId}">
            <f:selectItem itemLabel="  " noSelectionOption="true"/>
            <f:selectItems value="#{carsController.all}" var="car"
                           itemLabel="#{car.carBrand} #{car.number}" itemValue="#{car.id}"/>
        </h:selectOneMenu>
        <h:message for="car"/>

        <label>#{titles['entity.request.performer']}</label>
        <h:selectOneMenu id="performer" value="#{requestController.current.performerId}">
            <f:selectItem itemLabel="  " noSelectionOption="true"/>
            <f:selectItems value="#{transportersController.all}" var="performer"
                           itemLabel="#{performer.org.name}" itemValue="#{performer.id}"/>
        </h:selectOneMenu>
        <h:message for="performer"/>

        <label>#{titles['entity.request.customer']}</label>
        <h:selectOneMenu id="customer" value="#{requestController.current.customerId}">
            <f:selectItem itemLabel="  " noSelectionOption="true"/>
            <f:selectItems value="#{customersController.all}" var="customer"
                           itemLabel="#{customer.org.name}" itemValue="#{customer.id}"/>
            <f:ajax execute="@form" render="@form" event="valueChange"/>
        </h:selectOneMenu>
        <h:message for="customer"/>

        <label>#{titles['entity.request.route']}</label>
        <h:selectOneMenu id="requestRoute" value="#{requestController.current.routeId}">
            <f:selectItem itemValue="  " noSelectionOption="true"/>
            <f:selectItems value="#{customerController.getRoutes(requestController.current.customerId)}" var="r"
                    itemValue="#{r.id}" itemLabel="#{r.name}"/>
        </h:selectOneMenu>
        <h:message for="requestRoute"/>

        <label>#{titles['entity.request.shipper']}</label>
        <h:selectOneMenu id="shipper" value="#{requestController.current.shipperId}">
            <f:selectItem itemLabel="  " noSelectionOption="true"/>
            <f:selectItems value="#{customersController.all}" var="shipper"
                           itemLabel="#{shipper.org.name}" itemValue="#{shipper.id}"/>
        </h:selectOneMenu>
        <h:message for="shipper"/>

    </h:panelGrid>

</ui:composition>

src/main/webapp/sanctionView.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        >

    <h:panelGrid columns="3"
                 styleClass="png_details"
                 columnClasses="pngCol_lable, pngCol_input, pngCol_errors"
            >

        <label>#{titles['entity.sanctionText']}: </label>
        <h:inputText id="sanctionText" value="#{sanctionController.currentSanction.sanctionText}"/>
        <h:message for="sanctionText"/>

    </h:panelGrid>

</ui:composition>

src/main/webapp/sanctions.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="layout.xhtml"
        >
    <ui:define name="content">
        <label>#{titles['sanctions.count']} #{sanctionsController.count}</label>
        <br/>
        <h:link value="#{titles['button.create']}" outcome="createSanction"/>
        <br/>
        <h:dataTable value="#{sanctionsController.all}" var="sanc"
                     styleClass="tabl" headerClass="header"
                     rowClasses="tab_row_even, tab_row_odd"
                     columnClasses="col_name, col_fiction, col_edit, col_delete"
                >

            <h:column>
                <f:facet name="header">#{titles['entity.sanctionText']}</f:facet>
                #{sanc.sanctionText}
            </h:column>

            <h:column>
                <f:facet name="header"></f:facet>
            </h:column>

            <h:column>
                <h:form>
                    <h:commandLink value="#{titles['button.edit']}"
                                   action="#{sanctionsController.edit(sanc.id)}"/>
                </h:form>
            </h:column>

            <h:column>
                <h:form>
                    <h:commandLink value="#{titles['button.delete']}"
                                   action="#{sanctionsController.delete(sanc.id)}"/>
                </h:form>
            </h:column>

        </h:dataTable>
    </ui:define>
</ui:composition>